### PR TITLE
Fix for time dependency 1.9.*

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by psibi** [comment]
@smurphy8 Can this be merged and a new release be made ?

**Comment by smurphy8** [comment]
@psibi I merged and released, thank you!

Just curious are you using herf time?

**Comment by psibi** [comment]
@smurphy8 Thanks for the release! Yes, it's being used in one of our internal software (closed source).

**Comment by smurphy8** [comment]
Well great!

**Pull request merged**
